### ISSUE TITLE
setup error 

### ISSUE THREAD

**Issue by 7aduta** [tamaspiros/advanced-chat#12]
when i try to setup localy i get this error

> ws@0.4.31 install C:\Users\Mohamed\Desktop\ya rab\node_modules\socket.io\node_
modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Mohamed\Desktop\ya rab\node_modules\socket.io\node_modules\socket.io-cl
ient\node_modules\ws>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp
-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
/
> chat@0.0.1 postinstall C:\Users\Mohamed\Desktop\ya rab
> ./node_modules/bower/bin/bower install

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! chat@0.0.1 postinstall: `./node_modules/bower/bin/bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chat@0.0.1 postinstall script.
npm ERR! This is most likely a problem with the chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/bower/bin/bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls chat
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Mohamed\Desktop\ya rab
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Mohamed\Desktop\ya rab\npm-debug.log
npm ERR! not ok code 0

any help please ?

**Comment by tamaspiros** [comment]
on a windows machine open up package.json and remove the 'postinstall' bit from here:

scripts": {
    "postinstall": "./node_modules/bower/bin/bower install",
    "start": "node server.js"
  },

install bower (if you don't have it already) manually by running `npm install bower -g` and in the project's root folder execute `bower install`. - this will install the frontend dependencies.
