### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by Egorvoz** [tamaspiros/advanced-chat#17]
i did all instructions but it doesn't work.

info - socket.io started
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
warn - error raised: Error: listen EADDRINUSE

and crush CSS.

**Comment by tamaspiros** [comment]
The error message implies that the port the you're trying to run is already being used by something else. Try to change the port number and see if that helps
