### ISSUE TITLE
Um I get an issue with chat @0.01

### ISSUE THREAD

**Issue by Shereen161** [tamaspiros/advanced-chat#18]
this is the debug log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.28
3 info using node@v0.10.35
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart chat@0.0.1
7 info start chat@0.0.1
8 verbose unsafe-perm in lifecycle true
9 info chat@0.0.1 Failed to exec start script
10 error chat@0.0.1 start: `node server.js`
10 error Exit status 1
11 error Failed at the chat@0.0.1 start script.
11 error This is most likely a problem with the chat package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     node server.js
11 error You can get their info via:
11 error     npm owner ls chat
11 error There is likely additional logging output above.
12 error System Windows_NT 6.1.7601
13 error command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error cwd C:\Users\Sharon\Desktop\advanced-chat-master
15 error node -v v0.10.35
16 error npm -v 1.4.28
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

**Comment by tamaspiros** [comment]
Did you install all the dependencies?

**Comment by Shereen161** [comment]
Yup I did

**Comment by Shereen161** [comment]
and got a new log . . . . . . . . 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.4.28
3 info using node@v0.10.35
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 info shrinkwrap file "C:\\Users\\Sharon\\Desktop\\advanced-chat-master\\npm-shrinkwrap.json"
6 verbose readDependencies returned deps { ejs: 'https://registry.npmjs.org/ejs/-/ejs-0.8.8.tgz',
6 verbose readDependencies returned deps   express: '3.4.8',
6 verbose readDependencies returned deps   'node-uuid': 'https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.3.tgz',
6 verbose readDependencies returned deps   nodemon: 'https://registry.npmjs.org/nodemon/-/nodemon-1.0.20.tgz',
6 verbose readDependencies returned deps   npid: '0.4.0',
6 verbose readDependencies returned deps   'socket.io': 'https://registry.npmjs.org/socket.io/-/socket.io-0.9.17.tgz',
6 verbose readDependencies returned deps   shrinkwrap: '0.0.3',
6 verbose readDependencies returned deps   underscore: '1.5.2',
6 verbose readDependencies returned deps   bower: '1.2.8' }
7 verbose install where, deps [ 'C:\\Users\\Sharon\\Desktop\\advanced-chat-master',
7 verbose install   [ 'ejs',
7 verbose install     'express',
7 verbose install     'node-uuid',
7 verbose install     'nodemon',
7 verbose install     'npid',
7 verbose install     'socket.io',
7 verbose install     'shrinkwrap',
7 verbose install     'underscore',
7 verbose install     'bower' ] ]
8 info preinstall chat@0.0.1
9 warn package.json shrinkwrap@0.0.3 No README data
10 info shrinkwrap file "C:\\Users\\Sharon\\Desktop\\advanced-chat-master\\npm-shrinkwrap.json"
11 verbose readDependencies returned deps { ejs: 'https://registry.npmjs.org/ejs/-/ejs-0.8.8.tgz',
11 verbose readDependencies returned deps   express: '3.4.8',
11 verbose readDependencies returned deps   'node-uuid': 'https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.3.tgz',
11 verbose readDependencies returned deps   nodemon: 'https://registry.npmjs.org/nodemon/-/nodemon-1.0.20.tgz',
11 verbose readDependencies returned deps   npid: '0.4.0',
11 verbose readDependencies returned deps   'socket.io': 'https://registry.npmjs.org/socket.io/-/socket.io-0.9.17.tgz',
11 verbose readDependencies returned deps   shrinkwrap: '0.0.3',
11 verbose readDependencies returned deps   underscore: '1.5.2',
11 verbose readDependencies returned deps   bower: '1.2.8' }
12 verbose already installed skipping ejs@https://registry.npmjs.org/ejs/-/ejs-0.8.8.tgz C:\Users\Sharon\Desktop\advanced-chat-master
13 verbose already installed skipping express@3.4.8 C:\Users\Sharon\Desktop\advanced-chat-master
14 verbose already installed skipping node-uuid@https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.3.tgz C:\Users\Sharon\Desktop\advanced-chat-master
15 verbose already installed skipping nodemon@https://registry.npmjs.org/nodemon/-/nodemon-1.0.20.tgz C:\Users\Sharon\Desktop\advanced-chat-master
16 verbose already installed skipping npid@0.4.0 C:\Users\Sharon\Desktop\advanced-chat-master
17 verbose already installed skipping socket.io@https://registry.npmjs.org/socket.io/-/socket.io-0.9.17.tgz C:\Users\Sharon\Desktop\advanced-chat-master
18 verbose already installed skipping shrinkwrap@0.0.3 C:\Users\Sharon\Desktop\advanced-chat-master
19 verbose already installed skipping underscore@1.5.2 C:\Users\Sharon\Desktop\advanced-chat-master
20 verbose already installed skipping bower@1.2.8 C:\Users\Sharon\Desktop\advanced-chat-master
21 silly resolved []
22 info build C:\Users\Sharon\Desktop\advanced-chat-master
23 verbose linkStuff [ false, false, false, 'C:\\Users\\Sharon\\Desktop' ]
24 info linkStuff chat@0.0.1
25 verbose linkBins chat@0.0.1
26 verbose linkMans chat@0.0.1
27 verbose rebuildBundles chat@0.0.1
28 verbose rebuildBundles [ '.bin',
28 verbose rebuildBundles   '.gitkeep',
28 verbose rebuildBundles   'bower',
28 verbose rebuildBundles   'ejs',
28 verbose rebuildBundles   'express',
28 verbose rebuildBundles   'node-uuid',
28 verbose rebuildBundles   'nodemon',
28 verbose rebuildBundles   'npid',
28 verbose rebuildBundles   'shrinkwrap',
28 verbose rebuildBundles   'socket.io',
28 verbose rebuildBundles   'underscore',
28 verbose rebuildBundles   'underscore-node' ]
29 verbose rebuild bundle C:\Users\Sharon\Desktop\advanced-chat-master\node_modules\underscore-node
30 info build C:\Users\Sharon\Desktop\advanced-chat-master\node_modules\underscore-node
31 info preinstall underscore-node@0.1.2
32 verbose linkStuff [ false,
32 verbose linkStuff   false,
32 verbose linkStuff   false,
32 verbose linkStuff   'C:\\Users\\Sharon\\Desktop\\advanced-chat-master\\node_modules' ]
33 info linkStuff underscore-node@0.1.2
34 verbose linkBins underscore-node@0.1.2
35 verbose linkMans underscore-node@0.1.2
36 verbose rebuildBundles underscore-node@0.1.2
37 info install underscore-node@0.1.2
38 info postinstall underscore-node@0.1.2
39 info install chat@0.0.1
40 info postinstall chat@0.0.1
41 verbose unsafe-perm in lifecycle true
42 info chat@0.0.1 Failed to exec postinstall script
43 error chat@0.0.1 postinstall: `./node_modules/bower/bin/bower install`
43 error Exit status 1
44 error Failed at the chat@0.0.1 postinstall script.
44 error This is most likely a problem with the chat package,
44 error not with npm itself.
44 error Tell the author that this fails on your system:
44 error     ./node_modules/bower/bin/bower install
44 error You can get their info via:
44 error     npm owner ls chat
44 error There is likely additional logging output above.
45 error System Windows_NT 6.1.7601
46 error command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
47 error cwd C:\Users\Sharon\Desktop\advanced-chat-master
48 error node -v v0.10.35
49 error npm -v 1.4.28
50 error code ELIFECYCLE
51 verbose exit [ 1, true ]

**Comment by tamaspiros** [comment]
get rid of the `postinstall` property and manually execute `bower install` after you've done `npm install`

**Comment by tamaspiros** [comment]
I assume this has worked.
