### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by Perfect-Web** [tamaspiros/advanced-chat#19]
i have this chat running from a nginx proxy, and when i load it from the url everything works, but when i embed the script into my site and connect it doesnt work. 
Any idea ?

**Comment by Perfect-Web** [comment]
nevermind, this happens because it is using socket.io 0.9 this should be upgraded to the latest version of socket

**Comment by tamaspiros** [comment]
I haven't run this app embedded I'm afria.d If you ever figure it out please let me know.
