### ISSUE TITLE
No license information

### ISSUE THREAD

**Issue by Ovid** [tamaspiros/advanced-chat#24]
`advanced-chat` looks very useful for an internal project I'm working on, but without a license, I feel very uncomfortable relying on it. Anything "copy left", GPL, or so on pretty much precludes being able to use this. [Here's a useful StackOverflow discussion on this topic](http://stackoverflow.com/questions/28530/corporate-friendly-open-source-licenses).

Personally, I like the MIT license or Perl Artistic 2 licenses :)

**Comment by tamaspiros** [comment]
https://github.com/tamaspiros/advanced-chat/commit/99c2f25d083b55f62084de5a82b431d83dff4e38

:)

**Comment by Ovid** [comment]
:+1: You rock :)
