### ISSUE TITLE
Error when I start the server

### ISSUE THREAD

**Issue by bagusflyer** [tamaspiros/advanced-chat#25]
I got the following error message:

 > Error: EACCES, permission denied '/var/run/advanced-chat.pid

What could be wrong? Thanks.

**Comment by tamaspiros** [comment]
Please do a google search on EACCESS permission denied and check how your system is setup.

(e.g.: http://stackoverflow.com/questions/27475480/error-eacces-permission-denied-even-after-using-sudo)

**Comment by bagusflyer** [comment]
Don't quite under stand what's this regarding in your link. My error is different from the link.

> connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
{ [Error: EACCES, permission denied '/var/run/advanced-chat.pid']
  errno: -13,
  code: 'EACCES',
  path: '/var/run/advanced-chat.pid',
  syscall: 'open' }
