### ISSUE TITLE
Css problem

### ISSUE THREAD

**Issue by pradeepdtu** [tamaspiros/advanced-chat#31]
css problem and nothing is displayed when we type any message or create room

**Comment by tamaspiros** [comment]
check your developer tool logs - I need some error messages to be able to help you out.

**Comment by pradeepdtu** [comment]
Developer tool shows error like this:
Failed http://127.0.0.1:8000/components/font-awesome/css/font-awesome.css 
to load resource: the server responded with a status of 404 (Not Found)

**Comment by tamaspiros** [comment]
you probably miss the dependencies for the project - have you run `bower install`?

**Comment by pradeepdtu** [comment]
No, how to run bower install?

**Comment by tamaspiros** [comment]
As stated in my earlier comment `bower install`. If you don't have bower installed install it by `npm install -g bower`. For further info: http://bower.io/#getting-started

**Comment by pradeepdtu** [comment]
Still those errors are coming out.I think that's because in zip file there was no css file named font-awesome.css and also no folder named components

**Comment by tamaspiros** [comment]
after bower install do you get a folder 'bower_components'? if so, rename that to 'components'. If the error with the font-awesome.css still persist, get the css manually from https://fortawesome.github.io/Font-Awesome/

**Comment by pradeepdtu** [comment]
I have installed bower but i haven't got folder bower_components.
May you explain  how to configure bower.json?

**Comment by tamaspiros** [comment]
there's already a bower.json for this project - you don't need to add one. In the project's root folder you can go ahead and execute `bower install` and that should install the project dependencies. Please make sure you don't receive any errors while running the aforementioned command.

**Comment by pradeepdtu** [comment]
Actually 5 errors are still coming out. Two for bootstrap.css , font-awesome.css and other two are for jquery.js, bootstrap.js. I have installed bower but these errors are still coming out

**Comment by tamaspiros** [comment]
when you say 'I have installed bower' do you mean that you have actually installed bower (by executing `npm install bower -g`) or that you have installed the bower packages (by executing `bower install`)?

If you still have the errors fetch those dependencies manually and save them to your project - also go ahead and change the references in the `index.html` file.

**Comment by pradeepdtu** [comment]
I have installed bower both way globally and locally but there is no folder named bower_components.
Now i am updating bower.json by using command
$ bower install --save jquery bootstrap
Error comes like this...
bower ENOGIT        git is not installed or not in the PATH
what should i do?

**Comment by tamaspiros** [comment]
that's your issue at the first place - you need git installed as well. please google that.

**Comment by pradeepdtu** [comment]
thanks a lot, now everything is working perfectly.

**Comment by tamaspiros** [comment]
awesome - enjoy the app! :)
